"""
Tags for the `Faktura` model.
"""
FakturaTags = [
    {"name": "KodWaluty", "tag": "ns1:KodWaluty", "type": "string"},
    {"name": "P_1", "tag": "ns1:P_1", "type": "date"},
    {"name": "P_2A", "tag": "ns1:P_2A", "type": "string"},
    {"name": "P_3A", "tag": "ns1:P_3A", "type": "string100"},
    {"name": "P_3B", "tag": "ns1:P_3B", "type": "string200"},
    {"name": "P_3C", "tag": "ns1:P_3C", "type": "string100"},
    {"name": "P_3D", "tag": "ns1:P_3D", "type": "string200"},
    {"name": "P_4A", "tag": "ns1:P_4A", "type": "string"},
    {"name": "P_4B", "tag": "ns1:P_4B", "type": "string"},
    {"name": "P_5A", "tag": "ns1:P_5A", "type": "string"},
    {"name": "P_5B", "tag": "ns1:P_5B", "type": "string"},
    {"name": "P_6", "tag": "ns1:P_6", "type": "date"},
    {"name": "P_13_1", "tag": "ns1:P_13_1", "type": "float"},
    {"name": "P_14_1", "tag": "ns1:P_14_1", "type": "float"},
    {"name": "P_14_1W", "tag": "ns1:P_14_1W", "type": "float"},
    {"name": "P_13_2", "tag": "ns1:P_13_2", "type": "float"},
    {"name": "P_14_2", "tag": "ns1:P_14_2", "type": "float"},
    {"name": "P_14_2W", "tag": "ns1:P_14_2W", "type": "float"},
    {"name": "P_13_3", "tag": "ns1:P_13_3", "type": "float"},
    {"name": "P_14_3", "tag": "ns1:P_14_3", "type": "float"},
    {"name": "P_14_3W", "tag": "ns1:P_14_3W", "type": "float"},
    {"name": "P_13_4", "tag": "ns1:P_13_4", "type": "float"},
    {"name": "P_14_4", "tag": "ns1:P_14_4", "type": "float"},
    {"name": "P_14_4W", "tag": "ns1:P_14_4W", "type": "float"},
    {"name": "P_13_6", "tag": "ns1:P_13_6", "type": "float"},
    {"name": "P_13_7", "tag": "ns1:P_13_7", "type": "float"},
    {"name": "P_15", "tag": "ns1:P_15", "type": "float"},
    {"name": "P_16", "tag": "ns1:P_16", "type": "boolean"},
    {"name": "P_17", "tag": "ns1:P_17", "type": "boolean"},
    {"name": "P_18", "tag": "ns1:P_18", "type": "boolean"},
    {"name": "P_18A", "tag": "ns1:P_18A", "type": "boolean"},
    {"name": "P_19", "tag": "ns1:P_19", "type": "boolean"},
    {"name": "P_20", "tag": "ns1:P_20", "type": "boolean"},
    {"name": "P_21", "tag": "ns1:P_21", "type": "boolean"},
    {"name": "P_22", "tag": "ns1:P_22", "type": "boolean"},
    {"name": "P_23", "tag": "ns1:P_23", "type": "boolean"},
    {"name": "P_106E_2", "tag": "ns1:P_106E_2", "type": "boolean"},
    {"name": "P_106E_3", "tag": "ns1:P_106E_3", "type": "boolean"},
    {"name": "RodzajFaktury", "tag": "ns1:RodzajFaktury", "type": "string"}
]
